menu:
    Blog: /
    Archive: /archives/
    # Weibo: http://weibo.com/lelar
    GitHub: https://github.com/iLeyar
    Rss: /atom.xml

favicon: /images/favicon.ico
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: ileyar
# duoshuo:

# Analytics
# google-analytics:
ga: UA-74627504-2

# Copyright Infomation
startyear: 2011
